# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Schematic Capture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Schematic Capture
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'GoogleSignIn'
pod 'SCLAlertView'
pod 'ExpyTableView'
pod 'SwiftyDropbox'


  target 'Schematic CaptureTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
