name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      working-directory: "Schematic Capture"
    - name: Run tests
      run: swift test -v
      working-directory: "Schematic Capture"
